# Generated by Django 5.0.3 on 2024-03-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('apply_promo_code', 'Peut appliquer des migrations')], 'verbose_name': 'Livre', 'verbose_name_plural': 'Livres'},
        ),
    ]
